=== T1DEe/Java-Labs/Java_Lab03/files/car.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="arrayCar">
        <xs:complexType>

            <xs:element name="CarHeavy">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="manufacturer" type="xs:string"/>
                            <xs:element name="length" type="xs:int"/>
                            <xs:element name="weight" type="xs:int"/>
                            <xs:element name="wheelDrive" type="xs:int"/>
                            <xs:element name="maxSpeed" type ="xs:int"/>
                            <xs:element name="fuelConsum" type="xs:int"/>
                            <xs:element name="price" type="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="CarLight">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="manufacturer" type="xs:string"/>
                            <xs:element name="length" type="xs:int"/>
                            <xs:element name="weight" type="xs:int"/>
                            <xs:element name="wheelDrive" type="xs:int"/>
                            <xs:element name="maxSpeed" type ="xs:int"/>
                            <xs:element name="fuelConsum" type="xs:int"/>
                            <xs:element name="price" type="xs:int"/>
                            <xs:element name="seatingPlaces" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

        </xs:complexType>
    </xs:element>

</xs:schema>

=== T1DEe/Java-Labs/Java_Lab03/files/car.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type= "text/xsl" version="2.0" href = "air.xsl"?>
<arrayCar  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="car.xsd">
    <CarHeavy>
        <manufacturer>Volvo</manufacturer>
        <length>800</length>
        <weight>5500</weight>
        <wheelDrive>1</wheelDrive>
        <maxSpeed>150</maxSpeed>
        <fuelConsum>32</fuelConsum>
        <price>35000</price>
        <capacity>10</capacity>
    </CarHeavy>
    <CarLight>
        <manufacturer>Mercedes Benz</manufacturer>
        <length>500</length>
        <weight>3</weight>
        <wheelDrive>2</wheelDrive>
        <maxSpeed>220</maxSpeed>
        <fuelConsum>20</fuelConsum>
        <price>82000</price>
        <seatingPlaces>5</seatingPlaces>
    </CarLight>
    <CarLight>
        <manufacturer>Nissan</manufacturer>
        <length>300</length>
        <weight>2200</weight>
        <wheelDrive>2</wheelDrive>
        <maxSpeed>250</maxSpeed>
        <fuelConsum>16</fuelConsum>
        <price>55000</price>
        <seatingPlaces>5</seatingPlaces>
    </CarLight>
</arrayCar>
